yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    # Об авторе
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    # О проекте
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страницы сообществ
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр поста
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание поста
    path('create/', views.post_create, name='post_create'),
    # Редактирование поста
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # Добавление комментария к посту
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    # Страница с постами авторов на которых подписан пользователь
    path('follow/', views.follow_index, name='follow_index'),
    # Подписаться
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    # Отписаться
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Главная страница обрабатывается вью-функцией index() из приложения Posts
    path('', include('posts.urls', namespace='posts')),

    # Встроенная админка
    path('admin/', admin.site.urls),

    # Кастомный модуль авторизации пользователей
    path('auth/', include('users.urls')),

    # Встроенный модуль авторизации пользователей
    path('auth/', include('django.contrib.auth.urls')),

    # О проекте
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from core.models import CreatedModel

# Количество символов при вызове метода __str__ модели Post
COUNT_SYMBOLS = settings.COUNT_SYMBOLS_POST

User = get_user_model()


class Post(CreatedModel):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def get_absolute_url(self):
        return reverse('posts:post_detail', args=(self.pk, ))

    def __str__(self):
        # выводим текст поста
        return self.text[:COUNT_SYMBOLS]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def get_absolute_url(self):
        return reverse('posts:group_list', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


class Comment(CreatedModel):
    text = models.TextField(
        verbose_name='Текст комментария',
    )
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )

    def __str__(self):
        return self.text[:COUNT_SYMBOLS]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    def __str__(self):
        return f'{self.author}-{self.user}'

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['author', 'user'],
                                    name='unique_follow')
        ]

yatube/posts/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Comment, Post


# Форма создания поста
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        data = self.cleaned_data['text']

        if len(data) < 5:
            raise ValidationError('Слишком короткий пост')
        return data


# Форма создания комментария
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from core.utils import get_pages
from .forms import CommentForm, PostForm
from .models import Follow, Group, Post

User = get_user_model()


# Главная страница
@cache_page(20, key_prefix='index_page')
def index(request):
    """Получаем все посты и выводим используя паджинатор get_pages."""
    posts = Post.objects.select_related('author', 'group').all()
    page_obj = get_pages(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


# Страница с постами отфильрованными по группам
def group_posts(request, slug):
    """
    По полученной slug строке получаем название группы,
    через related_name 'posts' получаем все посты выбранной группы,
    выводим с паджинацией get_pages.
    """
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author').all()
    page_obj = get_pages(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


# Страница профиля со списком постов
def profile(request, username):
    """
    По полученной строке забираем имя пользователя,
    через related_name 'posts' получаем все его посты,
    выводим с паджинацией get_pages.
    """
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group').all()
    page_obj = get_pages(request, posts)
    following = (request.user.is_authenticated
                 and Follow.objects.filter(author=author,
                                           user=request.user).exists())

    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


# Страница с выбранным постом
def post_detail(request, post_id):
    """
    Получаем пост по pk, через ForeignKey-author полученного поста
    возвращаем текст посата и общее количество постов автора.
    """
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    count_posts = post.author.posts.all().count()
    form = CommentForm()
    context = {
        'post': post,
        'count_posts': count_posts,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


# Создание поста
@login_required
def post_create(request):
    """
    Если не POST, создаем пустую форму.

    Если POST, передаем данные в объект form, проверяем на валидность,
    создаем объект поста, заполняем у него абрибут author,
    сохраняем новый пост в БД.

    После сохранения пользователь перенапавляется на страницу своего профиля.
    """
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', username=request.user.username)
    context = {
        'form': form,
    }
    return render(request, "posts/create_post.html", context)


# Редактирование поста
@login_required
def post_edit(request, post_id):
    """
    По полученному post_id забираем пост из БД.
    Если не POST, добавляем в объект формы данные из
    запрошенного поста.
    is_edit - для корректной генерации кнопок и названий формы
    при использовании одного шаблона.
    post_id - в context для генерации ссылки на редактирование.

    Если POST и валидна, сохраняем в БД.
    Если POST и не валидна, возвращаем пользователю.

    После сохранения пользователь перенапавляется на страницу своего профиля.
    """
    post = get_object_or_404(Post, id=post_id)

    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': True,
        'post_id': post.id
    }
    return render(request, 'posts/create_post.html', context)


# Добавление коментария к посту
@login_required
def add_comment(request, post_id):
    """Добавляет комментарий к посту."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Выводит список постов авторов, на которых подписан пользователь."""
    user = get_object_or_404(User, username=request.user)
    # Все посты авторов
    posts = Post.objects.filter(author__following__user=user)
    page_obj = get_pages(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Подписка на автора."""
    author = get_object_or_404(User, username=username)
    follower = request.user

    if author != follower:
        Follow.objects.get_or_create(
            author=author, user=follower
        )
    return redirect('posts:profile', username=author.username)


@login_required
def profile_unfollow(request, username):
    """Отписка от автора."""
    author = get_object_or_404(User, username=username)

    Follow.objects.filter(
        author=author, user=request.user
    ).delete()
    return redirect('posts:profile', username=author.username)

yatube/templates/posts/create_post.html
<!-- templates/posts/create_post.html -->

{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
              {% if is_edit %}
                Редактировать запись
              {% else %}
                Добавить запись
              {% endif %}
          </div>
          <div class="card-body">
            {% include 'core/errors.html' %}
            <form method="post" enctype="multipart/form-data"
              {% if is_edit %}
                action="{% url 'posts:post_edit' post_id %}"
              {% else %}
                action="{% url 'posts:post_create' %}"
              {% endif %}
              >
              {% csrf_token %}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small 
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted"
                    >
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
<!-- templates/follow.html -->

{% extends 'base.html' %}
{% block title %}
  Избранные авторы
{% endblock %}
{% block content %}
  {% load thumbnail %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    <h1>Избранные авторы</h1>
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      {% if post.group %}
        <a
          href="{% url 'posts:group_list' post.group.slug %}"
        >все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
<!-- templates/group_list.html -->

{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
  {% load thumbnail %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
<!-- templates/index.html -->

{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      {% if post.group %}
        <a
          href="{% url 'posts:group_list' post.group.slug %}"
        >все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
<!-- templates/posts/post_detail.html -->

{% extends 'base.html' %}
{% block title %}
  Пост {{ post|truncatechars:30 }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.created|date:"d E Y" }}
          </li>
          <!-- если у поста есть группа -->   
          <li class="list-group-item">
            {% if post.group %}
              Группа: {{ post.group }}
              <a href="{{ post.group.get_absolute_url }}">
                все записи группы
              </a>
            {% else %}
              Группа: отсутствует
            {% endif %}
          </li>
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора: <span>{{ count_posts }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% load thumbnail %}
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}
        {% if post.author == user %}</p>
          <a class="btn btn-primary"
             href="{% url 'posts:post_edit' post.id %}"
          >
            редактировать запись
          </a>
        {% endif %}
        {% include 'posts/includes/comments.html' %}
      </article>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
<!-- templates/posts/profile.html -->

{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }} </h1>
      <h3>Всего постов: {{ page_obj.paginator.count }} </h3>
      {% if author != user %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
       {% endif %}
      {% endif %}
    </div>
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      <a 
        href="{{ post.get_absolute_url }}"
      >подробная информация</a>
      {% if post.group %}
        <a 
          href="{{ post.group.get_absolute_url }}"
        >все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}